-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        resize_on_border = true,
    },
})

-- Monitors
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "1920x1080@239.76Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
